### ISSUE TITLE
Make previous versions of HTML and XHTML obsolete

### ISSUE THREAD

**Issue by LJWatson** [w3ctag/obsoletion#1]
The WebPlat WG would welcome comment from the TAG on the [proposal to make previous versions of HTML and XHTML obsolete](https://github.com/w3c/WebPlatformWG/issues/86) that is out for CFC with the WG.

Though the WebPlat WG effectively maintains both HTML and XHTML, we wanted to invite comment from the TAG as part of our first foray into spec obsolesence.

The WG CFC closes on Tuesday 18th July 2017.

**Comment by cynthia** [comment]
Discussed in the London F2F - for the time being we are considering obsoleting everything under major version 5 (as there won't be any objections on that) - timeline and process is still under discussion.

**Comment by cynthia** [comment]
It seems like this has already been handled, but feel free to reopen in the event there needs a formal statement/recommendation from the TAG about this. (Will close if @LJWatson is happy with this.)

**Comment by travisleithead** [comment]
HTML has a long history of evolution through these past W3C standards. Many of these standards build on and extend each other, enriching the core platform and resulting in current specs that are highly conscious of past features required to have an interoperable web. (For example current versions of HTML include sections for obsolete features which are still required to support for backward compatibility.) For this reason, current versions of HTML include the relevant parts of past (now obsolete) features.

We believe it is important to ensure that implementations and the commmunity at large are referencing the latest versions of HTML as it continues to develop (see TAG finding on the [Evergreen Web](https://www.w3.org/2001/tag/doc/evergreen-web/)). A significant step toward this goal is to obsolete the specs listed above. The TAG is in favor of taking this action.

To all legacy HTMLs, yes especially you XHTML, thanks for flying TAG--you have reached your final destination.

**Comment by travisleithead** [comment]
Note: In the absence of additional feedback, we plan to close this issue.

**Comment by cynthia** [comment]
Got a hold of the WG chair and this seems safe to close.

**Comment by LJWatson** [comment]
To confirm, this went to the AC and received objections. Those objections were not technical, and were resolved with the introduction of the Superseded state in Process 2018.

**Comment by dbaron** [comment]
This [did go to the AC](https://lists.w3.org/Archives/Member/w3c-ac-members/2017JulSep/0028.html), but through WG action rather than TAG action.
