### ISSUE TITLE
please mark old mathML specs superseded

### ISSUE THREAD

**Issue by chaals** [w3ctag/obsoletion#2]
Hello TAG!

I'm requesting that the TAG consider the following specification
  - Name: MathML versions 1 and 2
  - Specification URL: http://www.w3.org/TR/REC-MathML and http://www.w3.org/TR/MathML2/

be considered by the TAG for (choose one):
  - [x] Superseding (of a W3C Recommendation)

Because they were effectively replaced by MathML 3.0, as noted in https://lists.w3.org/Archives/Public/www-tag/2017Apr/0016.html

This specification was produced by the MathML Working Group which was
closed some time ago .

**Comment by dbaron** [comment]
Seems like it's worth reaching out to a bunch of the folks who were involved in MathML to check that they agree, even if the working group no longer exists.  (Say, chairs and editors?)

**Comment by cynthia** [comment]
Taken up during the Tokyo F2F, we have sent an official request to supersede MathML 1 and 2 with 3.

(In practice, it seems like [MathJax](https://www.mathjax.org/) seems to be more commonly used in the wild.)
