### ISSUE TITLE
Obsolete Widget family of specs

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/obsoletion#3]
Hello TAG!

I'm requesting that the TAG consider the following specification
  - Name: Widget specs
  - Specification URL: https://www.w3.org/TR/?title=widget

be considered by the TAG for (choose one):
  - [x] obsoleting (of a W3C Recommendation)
  - [ ] rescinding (of a W3C Recommendation)
  - [ ] restoring (of an Obsolete W3C Recommendation)
(see [§6.9 Obsoleting or Rescinding a W3C Recommendation](https://www.w3.org/Consortium/Process/#rec-rescind) of the Process for what this means)

Service workers and web manifest are better solutions to the same problem. We had a fun run with widgets, but now it's time 👋😭. 

This specification was produced by "Web Application Formats WG" which was
closed on: https://www.w3.org/2006/appformats/.

The following specifications have dependencies on this specification:
 - None that I know of... 

The following implementations of this specification are known:
 - Apache Cordoba
 - Apache Wookie 
 - Other implementations are gone...
 
There are some stats on usage here:
https://www.scnsoft.com/blog/apache-cordova-is-there-a-future-for-it

But rather old... at one point, it seemed like 6% of the Android store was composed of Cordova apps. No idea what it is now, but I imagine it's low (but still not bad! lol haters!).  In any case, it was not a "browser thing".

**Comment by swickr** [comment]
Specifically, there are 4 Recommendations, 3 Notes, and 1 abandoned WD:

Widget Interface Recommendation 2013-10-31
XML Digital Signatures for Widgets Recommendation 2013-04-18
Packaged Web Apps (Widgets) - Packaging and XML Configuration Recommendation 2012-11-27
Widget Access Request Policy Recommendation 2012-02-07

Widget URI scheme Note 2012-03-13
Requirement For Standardizing Widgets Note 2011-09-27

Widgets 1.0: The Widget Landscape Working Draft 2008-04-14

**Comment by dbaron** [comment]
This proposal [did go to the AC](https://lists.w3.org/Archives/Member/w3c-ac-members/2018JulSep/0035.html).
