### ISSUE TITLE
2D Context

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/obsoletion#5]
Hello TAG!

I'm requesting that the TAG consider the following specification:
  - [2D Context](https://w3c.github.io/2dcontext/)

be considered by the TAG for (choose one; see [§6.9 Obsoleting or Rescinding a W3C Recommendation](https://www.w3.org/Consortium/Process/#rec-rescind) of the Process for what this means):
  - [ ] obsoleting (of a W3C Recommendation)
  - [X] superseding (of a W3C Recommendation)
  - [ ] rescinding (of a W3C Recommendation)
  - [ ] restoring (of an Obsolete W3C Recommendation)

Part of HTML. 

This specification was produced by "W3C HTML working group" which was
closed on 2018.

The following specifications have dependencies on this specification:
 -  no idea. But they should point to HTML instead. 

The following implementations of this specification are known:
 - None. Browsers implement WHATWG HTML. 

If the recommended action is superseding, the newer version that
supersedes it is:
  - [HTML](https://html.spec.whatwg.org/#the-canvas-element)

**Comment by ylafon** [comment]
It is already approved, as part of https://www.w3.org/2019/04/WHATWG-W3C-MOU.html#transition
